[package]
name = "entity"
version = "0.12.0"
edition = "2024"
publish = false

[lib]
name = "entity"
path = "lib.rs"

[dependencies]
sea-orm = { workspace = true, features = ["macros", "with-chrono"] }
